#!/usr/bin/env python3
"""Bake the Clawd-Laptop Lottie into Sources/Clawd.swift.

The file is pixel art: every one of its 349 paths is an axis-aligned rectangle on a
50-unit grid, every transform is the identity, and the only animated property is each
group's fill opacity, held at 0 or 100. So a "Lottie runtime" here is a list of
rectangles plus one visibility bit per frame — no library, no rasteriser.

usage: tools/bake_clawd.py path/to/claude.json
"""
import json
import sys
from pathlib import Path

GRID = 50  # half an art pixel

src = json.load(open(sys.argv[1]))
frames = int(src["op"])

groups, colors = [], []
for layer in src["layers"]:
    for group in layer["shapes"]:
        rects, ci, vis = [], None, []
        for item in group["it"]:
            if item["ty"] == "sh":
                v = item["ks"]["k"]["v"]
                xs, ys = [p[0] for p in v], [p[1] for p in v]
                rects.append((min(xs), min(ys), max(xs) - min(xs), max(ys) - min(ys)))
            elif item["ty"] == "fl":
                c = tuple(item["c"]["k"])
                if c not in colors:
                    colors.append(c)
                ci = colors.index(c)
                o = item["o"]
                vis = ([k["s"][0] > 0 for k in o["k"]] if o["a"] == 1
                       else [o["k"] > 0] * frames)
        groups.append((ci, rects, vis))

flat = [r for _, rs, _ in groups for r in rs]
x0, y0 = min(r[0] for r in flat), min(r[1] for r in flat)
cell = lambda v: int(round(v / GRID))
w = max(cell(r[0] + r[2] - x0) for r in flat)
h = max(cell(r[1] + r[3] - y0) for r in flat)

lines = []
for ci, rects, vis in groups:
    mask = sum(1 << i for i, on in enumerate(vis[:frames]) if on)
    quads = ", ".join(f"{cell(x - x0)},{cell(y - y0)},{cell(cw)},{cell(ch)}"
                      for x, y, cw, ch in rects)
    lines.append(f"        ({ci}, 0x{mask:011x}, [{quads}]),")

swatches = ",\n".join(
    "        NSColor(hex: 0x%02X%02X%02X)" % tuple(round(c * 255) for c in col[:3])
    for col in colors)

out = f'''import AppKit

// Generated by tools/bake_clawd.py from the Clawd-Laptop Lottie — do not edit by hand.
//
// Pixel art on a half-pixel grid: {len(groups)} fill groups, each a set of rectangles that is
// either fully on or fully off in a given frame. `mask` is that on/off bit per frame.
enum Clawd {{
    static let frames = {frames}
    static let cellsWide = {w}, cellsHigh = {h}

    static let colors: [NSColor] = [
{swatches},
    ]

    /// (colour index, visible-in-frame bitmask, rects flattened as x, y, w, h in cells)
    static let groups: [(Int, UInt64, [Int])] = [
{chr(10).join(lines)}
    ]
}}

/// Draws one frame, top-left aligned in `box`, at `scale` points per cell.
/// Cells are y-down (Lottie), the context is y-up.
func drawClawd(frame: Int, at origin: NSPoint, scale: CGFloat) {{
    let bit = UInt64(1) << UInt64(((frame % Clawd.frames) + Clawd.frames) % Clawd.frames)
    let top = origin.y + CGFloat(Clawd.cellsHigh) * scale
    for (ci, mask, quads) in Clawd.groups where mask & bit != 0 {{
        Clawd.colors[ci].setFill()
        for i in stride(from: 0, to: quads.count, by: 4) {{
            NSRect(x: origin.x + CGFloat(quads[i]) * scale,
                   y: top - CGFloat(quads[i + 1] + quads[i + 3]) * scale,
                   width: CGFloat(quads[i + 2]) * scale,
                   height: CGFloat(quads[i + 3]) * scale).fill()
        }}
    }}
}}
'''
dest = Path(__file__).resolve().parent.parent / "Sources" / "Clawd.swift"
dest.write_text(out)
print(f"wrote {dest} — {len(groups)} groups, {len(flat)} rects, {frames} frames, {w}x{h} cells")
